blank_issues_enabled: false
contact_links:
  - name: I have a question or need support
    url: https://github.com/frandle82/adaptive-areas/discussions/categories/q-a
    about: We use GitHub for tracking bugs, check our Discussions' Q&A area questions and help.
  - name: Feature Request
    url: https://github.com/frandle82/adaptive-areas/discussions/categories/ideas-feature-requests
    about: Please use our Discussions' Feature Request area for making feature requests.
