---
name: "Draft Release"

on:
  push:
    branches:
      - "main"
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
      - edited

permissions:
  contents: read

jobs:
  update_release_draft:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
    steps:
      - uses: release-drafter/release-drafter@v7
        with:
          config-name: release-drafter.yml

  auto_label:
    if: github.event_name == 'pull_request_target'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: release-drafter/release-drafter/autolabeler@v7
        with:
          config-name: release-drafter.yml
